### ISSUE TITLE
Separate PAWN and SA:MP standard libraries.

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/samp-stdlib#1]
core, float, file, datagram (do you really need to keep that one - it doesn't work), string, and time, are original parts of the PAWN library.  Some libraries (read: amx_assembly*) might not need all the SA:MP parts if they are quite pure PAWN libraries.

\* That's not quite true.  I've modified the code to only use PAWN libraries and not include a_samp anywhere (except tests), but they still need `printf` and `format` in some functions for outputting data.  Newer versions of PAWN also have console.inc with `printf`, but still no format (annoyingly it is only used in one place, I even debated removing it and doing that string manually).

**Comment by Y-Less** [comment]
I didn't actually get to the point in the first post...

Have separate repositories for PAWN libraries and SA:MP libraries.  Could have the SA:MP one depend on the PAWN one.

**Comment by Southclaws** [comment]
I never thought of that, this makes perfect sense.

Originally this repo was just going to be a carbon copy of the SA:MP package but this does make sense - it does feel a bit "heavy" to pull in all the SA:MP related files just for some pure-Pawn testing. Though the fact that `print` is in the SA:MP part has always irked me a bit...

I've never properly considered using the package-management portion of sampctl on its own for non-samp projects, I always forget Pawn is its own language used in other things...

**Comment by Southclaws** [comment]
And saying that, I'll move this repo to the sampctl user and open the pawn-stdlib repo there too.

**Comment by Y-Less** [comment]
Agree on `print`, I actually changed amx_assembly last night to try and remove a_samp as much as possible (prompting this issue in the first place), and added `#tryinclude <console>`, which is in the standard library in later releases (and found `strformat` for `format`).

**Comment by Southclaws** [comment]
Created sampctl/pawn-stdlib
