### ISSUE TITLE
(error) symbol already defined: "printf"

### ISSUE THREAD

**Issue by sanpezlo** [Southclaws/samp-stdlib#28]
when trying to install the package sampctl/samp-stdlib:0.3.
and by including it I'm throwing out the error

C:\Sampctl\dependencies\samp-stdlib\a_samp.inc:57 (error) symbol already defined: "print"
C:\Sampctl\dependencies\samp-stdlib\a_samp.inc:58 (error) symbol already defined: "printf"

**Comment by Southclaws** [comment]
Currently, the best thing to do is use the latest commit from master branch and then add your own native declarations for 0.3.DL natives.
