### ISSUE TITLE
missing natives and callbacks

### ISSUE THREAD

**Issue by YashasSamaga** [Southclaws/samp-stdlib#5]
There are few natives and callbacks which are missing in the includes of SAMP server package. Here are few (if not all) of the missing natives and callbacks:

**Missing Natives:**
- IsValidVehicle(vehicleid)
- SendClientCheck
- gpci

**Missing Callbacks:**
- OnClientCheckResponse
- OnScriptCash

I am not sure if it is safe to include some of these natives and callbacks. They could have been intentionally omitted from the includes so that people don't get to see them. They could be deprecated in a future version or even completely removed as it was not a part of the official SAMP includes set. Moreover, there's a lot of rumors about some of those natives and callbacks.

**Comment by Southclaws** [comment]
As mentioned in #3, I've considered using branches to preserve the original libraries so we can make useful changes to the originals such as these. It would be so useful to finally have these things declared where they should be!

As far as I know, `IsValidVehicle` was just an oversight, `SendClientCheck` and `gpci` were intended to be "secret" but basically everyone knows about them so it's pointless to hide them. Same with `OnClientCheckResponse` but I'm not sure about `OnScriptCash` (is that meant to be `OnScriptCrash`?)

**Comment by YashasSamaga** [comment]
It's `OnScriptCash`.

> [0:07:33] \<Kye\> it doesn't do anything currently
> [0:11:50] \<Kye\> it's meant to show money increases from the GTA SA scm
> [0:11:54] \<Kye\> like ammunation, casino

It could still be broken.

**Comment by Southclaws** [comment]
Ah, that actually would be so useful, it's unfortunate that it doesn't work...
